Tensor basics

In [0]:
import torch

In [0]:
# GPU 사용가능한지
torch.cuda.is_available()

False

In [0]:
torch.empty(3)

tensor([3.2923e-35, 0.0000e+00, 1.4013e-45])


In [0]:
torch.empty(2,2)

tensor([[4.9892e-36, 0.0000e+00],
        [5.6052e-45, 0.0000e+00]])

In [0]:
torch.empty(2,3,3)

tensor([[[3.2984e-35, 0.0000e+00, 7.0065e-44],
         [6.7262e-44, 6.3058e-44, 6.7262e-44],
         [7.2868e-44, 6.3058e-44, 6.8664e-44]],

        [[7.1466e-44, 1.1771e-43, 6.7262e-44],
         [7.9874e-44, 8.1275e-44, 6.8664e-44],
         [7.2868e-44, 8.1275e-44, 7.0065e-44]]])

In [0]:
torch.rand(2,2)

tensor([[0.6120, 0.8118],
        [0.8927, 0.3641]])

In [0]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [0]:
torch.ones(2,3, dtype=torch.int) # dtype으로 지정가능

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [0]:
x=torch.zeros(2,3)

x.size()

torch.Size([2, 3])

In [0]:
torch.tensor([2.5,0.0])

tensor([2.5000, 0.0000])

In [0]:
x = torch.rand(2,2)
y = torch.rand(2,2)

print(torch.add(x,y)) # 일반적인 사칙연산
print(x+y)
# torch.mul
# torch.div
# ...

tensor([[1.2119, 0.7222],
        [1.4826, 1.6035]])
tensor([[1.2119, 0.7222],
        [1.4826, 1.6035]])


In [0]:
print(y)
y.add_(x) # _ (underbar) 를 통해 inplace 역할
print(y)

tensor([[0.4791, 0.0654],
        [0.7632, 0.7938]])
tensor([[1.2119, 0.7222],
        [1.4826, 1.6035]])


In [0]:
x = torch.rand(5,5)
print(x)
print(x[:,0]) # 원하는 row, col

tensor([[0.5039, 0.5166, 0.4238, 0.3334, 0.8141],
        [0.4728, 0.8816, 0.1796, 0.5847, 0.8979],
        [0.7034, 0.2201, 0.5343, 0.8164, 0.0191],
        [0.9762, 0.8652, 0.4825, 0.6170, 0.8413],
        [0.9371, 0.2943, 0.0647, 0.5907, 0.8713]])
tensor([0.5039, 0.4728, 0.7034, 0.9762, 0.9371])


In [0]:
# reshape

x = torch.rand(2,2)
print(x)

y = x.view(4)
print(y)

z = x.view(-1, 4)
print(z)

tensor([[0.5897, 0.9453],
        [0.8493, 0.9064]])
tensor([0.5897, 0.9453, 0.8493, 0.9064])
tensor([[0.5897, 0.9453, 0.8493, 0.9064]])


In [0]:
# convert numpy to torch.tensor
import numpy as np

a = torch.ones(5)
print(a)

b = a.numpy() # tensor to numpy
print(b)
print(type(b))

a.add_(1)
print(a)
print(b) # b도 변해버린다

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [0]:
a = np.ones(4)
print(a)
b = torch.from_numpy(a)
print(b)

a += 1
print(a)
print(b) # 여기도 마찬가지

[1. 1. 1. 1.]
tensor([1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2.]
tensor([2., 2., 2., 2.], dtype=torch.float64)


In [0]:
if torch.cuda.is_available():
    device = torch.device("cuda") # GPU 사용 가능 확인

x = torch.ones(4, device=device) # 처음부터 GPU로 만들기

y = torch.ones(5)
y = y.to(device) # GPU로 옮기기

z = x + y # GPU에서 계산

z = z.to("cpu") # 다시 CPU로 계산

In [0]:
# requires_grad
# 해당 tensor에서 grad 저장
# 다음 tutorial에서 배운다

x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
