In [0]:
import torch

requires_grad

In [0]:
x = torch.randn(3, requires_grad=True)
print(x)
print(x.grad)

y = x+2
print(y)

z = y*y*2
print(z)

z = z.mean() # 스칼라
print(z)

tensor([ 0.7367, -0.1329,  0.7211], requires_grad=True)
None
tensor([2.7366, 1.8671, 2.7211], grad_fn=<AddBackward0>)
tensor([14.9785,  6.9724, 14.8093], grad_fn=<MulBackward0>)
tensor(12.2534, grad_fn=<MeanBackward0>)


In [0]:
z.backward() # dz/dx
# requires_grad=True 안하면 backward() 에러 발생
# backward()시에 마지막이 스칼라가 되어야한다

print(x.grad)

tensor([2.9479, 3.8577, 3.1249])


In [0]:
# 이번에는 z가 스칼라가 아닌 경우
x = torch.randn(3, requires_grad=True)
y = x+2
z = y*y*2

v = torch.tensor([0.1, 1.0, 0.001])
z.backward(v) # v가 없으면 에러발생
print(x.grad)

tensor([1.3078e+00, 5.8424e+00, 4.9726e-03])


- x.requires_grad_(False)
- x.detach()
- with torch.no_grad():

In [0]:
# stop gradient 방법
# 따라서 prediction 할 때 사용

# x.requires_grad_(False)
# x.detach()
# with torch.no_grad():

x = torch.randn(3, requires_grad=True)
print(x)

x = torch.randn(3, requires_grad=True)
x.requires_grad_(False)
print(x)

x = torch.randn(3, requires_grad=True)
x.detach_()
print(x)

x = torch.randn(3, requires_grad=True)
with torch.no_grad():
    y = x + 2
    print(y)

tensor([ 1.0162,  0.5918, -0.4185], requires_grad=True)
tensor([ 1.9918, -0.2379,  0.9113])
tensor([-0.2051,  0.0445, -0.6908])
tensor([1.5224, 3.0651, 2.9491])


In [0]:
# backward는 누적된다. 따라서 정확한 gradient 계산을 위해서는
# 지워야 한다.

weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()

    model_output.backward()

    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [0]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()

    model_output.backward()

    print(weights.grad)

    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [0]:
# optimizer
# 나중에 model train시에는 이렇게 backprop한다.
weights = torch.ones(4, requires_grad=True)

optimizer = torch.optim.SGD(weights, lr=0.01)
optimizer.step()
optimizer.zero_grad()