In [0]:
import torch
import torch.nn as nn
import numpy as np

softmax

In [0]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)

x = np.array([2.0, 1.0, 0.1])
output = softmax(x)
print(output)

[0.65900114 0.24243297 0.09856589]


In [0]:
x = torch.tensor([2.0, 1.0, 0.1])
output = torch.softmax(x, dim=0)
print(output)

tensor([0.6590, 0.2424, 0.0986])


cross entropy

In [0]:
def ce(actual, predicted):
    loss = -np.sum(actual*np.log(predicted))
    return loss

Y = np.array([1,0,0]) # one hot encoding label

Y_pred_good = np.array([0.7, 0.2, 0.1]) # softmax를 지난 뒤로 가정
Y_pred_bad = np.array([0.1, 0.3, 0.6])

l1 = ce(Y, Y_pred_good)
l2 = ce(Y, Y_pred_bad)
print(f'l1 : {l1:.4f}')
print(f'l2 : {l2:.4f}')

l1 : 0.3567
l2 : 2.3026


In [0]:
loss = nn.CrossEntropyLoss()
# nn.CrossEntropyLoss 에 이미 softmax가 들어가 있다
# 중복사용하지 않게 주의하자!
# label에 대해 one hot encoding 하면 안된다

Y = torch.tensor([2,0,1]) # 3 sample

# nsamples * nclass = 3 * 3
Y_pred_good = torch.tensor([[0.1, 1.0, 2.1],[2.0, 1.0, 0.1],[1.0, 2.0, 0.1]])
print(Y_pred_good.shape)
Y_pred_bad = torch.tensor([[0.5, 2.0, 0.3],[2.0, 1.0, 0.1],[2.0, 1.0, 0.1]])

l1 = loss(Y_pred_good, Y)
l1 = loss(Y_pred_bad, Y)
print(l1.item())
print(l2.item())

_, prediction1 = torch.max(Y_pred_good, 1)
_, prediction2 = torch.max(Y_pred_bad, 1)
print(prediction1) # 예측 잘함
print(prediction2) 

torch.Size([3, 3])
1.2915587425231934
2.3025850929940455
tensor([2, 0, 1])
tensor([1, 0, 0])


class로 구현

In [0]:
# multiclass
class NN(nn.Module):
    def __init__(self, input_size, hidden_size, num_class):
        super().__init__()
        self.Linear1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.Linear2 = nn.Linear(hidden_size, num_class)

    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        return out

model = NN(input_size=28*28, hidden_size=5,num_class=5)
criterion = nn.CrossEntropyLoss()

In [0]:
# binary class
class NN(nn.Module):
    def __init__(self, input_size, hidden_size):
        super().__init__()
        self.Linear1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.Linear2 = nn.Linear(hidden_size, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out = self.linear1(x)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out) # binary의 경우 마지막에 sigmoid layer
        return out

model = NN(input_size=28*28, hidden_size=5)
criterion = nn.BCELoss() # Binary Cross Entropy Loss